#!/usr/bin/env ruby
begin
  page, per_page = ARGV
  page = 1 if page.nil?
  per_page = 30 if per_page.nil?
  until Activity.fetch_activities(page, per_page).nil?
    page += 1
  end
rescue
  puts "Problem creating all activities."
end