#!/usr/bin/env ruby

def find_leaderboard_entry(activity)
  Leaderboard.where(athlete_id: activity.athlete_id,
                    activity_date_local: activity.start_date_only).first
end

def create_new_entry_for_athlete(activity)
  athlete = Athlete.find(activity.athlete_id)
  l_entry = Leaderboard.create(
    athlete_id: athlete.id, activity_date_local: activity.start_date_only,
    calories: activity.calories, beers: activity.beers,
    img_url: athlete.img_url, athlete_name: athlete.name
  )
  l_entry.activities << activity
end

def update_existing_with_activity(l_entry, activity)
  l_entry.calories += activity.calories
  l_entry.beers    = Activity.calc_beers(l_entry.calories)
  l_entry.save
  l_entry.activities << activity
end

Activity.find_each do |activity|
  if l_entry = find_leaderboard_entry(activity)
    update_existing_with_activity(l_entry, activity) unless l_entry.activities.include?(activity)
  else
    create_new_entry_for_athlete(activity)
  end
end
